// --- IDs DE REDE GLOBAIS (RPC) ---
const int ALP_RPC_GAME      = 2120579;
const int ALP_RPC_PLAYER    = 2120580;

const int ALP_RPC_PLAYER_SYNC_BIT               = 2120581;
const int ALP_RPC_PLAYER_SYNC_VALUE             = 2120582;
const int ALP_RPC_DAYZ_SKILLS_SPECIALTY_SYNC    = 2120583;

// --- TIPOS DE RPC DE JOGO ---
enum ALP_RPC_PLAYER_TYPE
{
    HIVE_SYNC_ALL,
    HIVE_SYNC_SMALL,
    SYNC_REGISTER_ENHANCEDSTATS,
}

enum ALP_RPC_GAME_TYPE
{
    INIT,
    SYNC,
}

// --- RPC PARA NOTIFICAÇÕES (NOTF) ---
enum ALP_RPC_PLUGIN_NOTF
{
    SM,
    MISSION,
    MOSTWANTED,
    PERSONAL,
    MESSAGE,
    MESSAGE_POSITION,
    MESSAGE_RAID_ALERT,
    QUEST_START,
    QUEST_END,
}

// --- RPC PARA SISTEMA DE MISSÕES (MS) ---
enum ALP_RPC_PLUGIN_MS
{
    SERVER_TIME,
    VERIFY_CLIENT,
    MISSIONS_TO_CLIENT,
    UPDATE,
    UPDATE_ALL,
    REGISTER_MISSION,   
    UPDATE_SETTING,
    INOUT,
    TRADER,
    NPC_QUESTS,
}

// --- RPC PARA ECONOMIA E TRADER (MS_TRADER) ---
enum ALP_RPC_PLUGIN_MS_TRADER
{
    GIVE_ME_ALL_STOCK,
    UPDATE_THESE_ITEMS,
    BUY_ITEMS,
    SELL_ITEMS,
    GIVE_ME_ACCOUNT,
    CARD_CHANGE_PASSWORD,
    CARD_BLOCK,
    ATM_CASH,
    ATM_TAKELOAN,
    ATM_REPAYLOAN,
    ATM_EXCHANGE,
    SPREAD_RUMOURS,
    ME_CURE_DISEASE,
    ME_DNA_SAVE,
    ME_DNA_LOAD
    // Note: Removidos RPCs de PlotPole/Estates para manter a limpeza sem o ND_Clans
}

// --- RPC PARA ROLEPLAY (RP) ---
enum ALP_RPC_PLUGIN_RP
{
    RECORDS,
    GAINED_EXP,
}