// IDs Globais de Comunicação
const int ALP_RPC_GAME = 2120579;
const int ALP_RPC_PLAYER = 2120580;

enum ALP_RPC_PLUGIN_MS_TRADER {
    PP_TAXES,
    ESTATE_BUY,
    ESTATE_SELL,
    ESTATE_BUY_KEY,
    ESTATE_UPDATE_SETTINGS,
    PP_PERMISSION
}

enum ALP_RPC_PLUGIN_CLANS {
    SET_CLAN_ID,
    CREATENEWCLAN,  
    SEND_CLAN_TO_CLIENT,
    UPDATE_ONLINE_MEMBERS,
    DISBAND_CLAN,
    LEAVE_CLAN,
    KICK_HIM,
    MATE_POSITION,
    SYNC_PLOTPOLE
}